[package]
name = "aoc-2024-13"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
common = { path = "../../common" }
regex = { version = "1.11", default-features = false, features = ["std", "perf"] }