[package]
name = "aoc-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
glam = { version = "0.29.2" , optional = true}


[features]
default = ["day09"]

#day08 = []
day09 = []
day10 = []