[package]
name = "aoc-2024-11"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
common = { path = "../../common" }
bytesize = "1.3.0"
bitvec = "1.0.1"
size-of = { version = "0.1.5" , features = ["hashbrown"]}
hashbrown = "0.13.2"
zstd = "0.13.2"